/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyListRouteImport } from './routes/company/list'
import { Route as CompanyCompanyIdRouteImport } from './routes/company/$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyListRoute = CompanyListRouteImport.update({
  id: '/company/list',
  path: '/company/list',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdRoute = CompanyCompanyIdRouteImport.update({
  id: '/company/$companyId',
  path: '/company/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/company/list': typeof CompanyListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/company/list': typeof CompanyListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/company/list': typeof CompanyListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/company/$companyId' | '/company/list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/company/$companyId' | '/company/list'
  id: '__root__' | '/' | '/company/$companyId' | '/company/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyCompanyIdRoute: typeof CompanyCompanyIdRoute
  CompanyListRoute: typeof CompanyListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/list': {
      id: '/company/list'
      path: '/company/list'
      fullPath: '/company/list'
      preLoaderRoute: typeof CompanyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyCompanyIdRoute: CompanyCompanyIdRoute,
  CompanyListRoute: CompanyListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
